# Generated by Django 4.1.2 on 2022-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, upload_to="blog/%Y/%m/%d"),
        ),
    ]
