# Generated by Django 4.1.2 on 2022-11-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image",
        ),
    ]
